Repository truenas/midcli, pull requests merged in 2022-12, with the labels that each got.

#69 NAS-119336 / 23.10 / Rootless login changes
  midcli/__main__.py
  midcli/menu/items.py
Labels: backport-22.12.0, backport-22.12.1

#74 NAS-119651 / 23.10 / add cli_console to console_scripts
  midcli/__main__.py
  setup.py
Labels: backport-22.12.1

#72 NAS-119307 / 22.12.1 / Do not print `<null>` if method is declared to return nothing
  midcli/command/call_mixin/__init__.py
  midcli/command/generic_call/__init__.py
Labels: backport-23.10
